name: youtube_clone
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  lottie: ^3.3.1
  shared_preferences: ^2.3.5
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  share_plus: ^10.1.4
  flutter_downloader: ^1.11.8
  shimmer: ^3.0.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  dio: ^5.7.0
  path_provider: ^2.1.5
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_secure_storage: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_animation.json
    - assets/logo.png
